/**
 * One-off parser: reads the curated product list text file and emits a typed
 * TypeScript data module at src/lib/product-data.ts.
 *
 * Run with: bun run scripts/parse-products.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SRC = resolve(process.cwd(), "upload/fitfeky_products_172.txt");
const OUT = resolve(process.cwd(), "src/lib/product-data.ts");

const raw = readFileSync(SRC, "utf8");

// Split into product blocks. Each block starts with "--- PRODUCT #N ---".
const blocks = raw
  .split(/^--- PRODUCT #\d+ ---[ \t]*$/m)
  .map((b) => b.trim())
  .filter((b) => b.length > 0);

const FIELD_LABELS = [
  "ASIN",
  "Title",
  "Category",
  "Price",
  "Rating",
  "Image",
  "URL",
  "Priority",
  "Quality Score",
  "Main Keyword",
  "Secondary Keywords",
  "Long-tail Keywords",
  "Suggested Calculator",
] as const;

type FieldLabel = (typeof FIELD_LABELS)[number];

function parseFields(block: string): Record<FieldLabel, string> {
  const result = {} as Record<FieldLabel, string>;
  const lines = block.split(/\n/);
  for (const line of lines) {
    for (const label of FIELD_LABELS) {
      const prefix = `${label}:`;
      if (line.startsWith(prefix)) {
        result[label] = line.slice(prefix.length).trim();
      }
    }
  }
  return result;
}

type Parsed = {
  id: string;
  asin: string;
  title: string;
  category: string;
  price: number | null;
  priceDisplay: string | null;
  rating: number | null;
  reviews: number | null;
  image: string;
  affiliateUrl: string;
  priority: "A" | "B" | "C";
  qualityScore: number;
  mainKeyword: string;
  secondaryKeywords: string[];
  longTailKeywords: string[];
  suggestedCalculator: string | null;
};

const products: Parsed[] = [];
let issues = 0;

for (const block of blocks) {
  const f = parseFields(block);
  const asin = f.ASIN ?? "";
  if (!asin || !f.Title || !f.URL) {
    // skip the header/statistics block and any malformed entries
    issues++;
    continue;
  }

  // Price: "$44.99" -> 44.99 ; "N/A" -> null
  let priceValue: number | null = null;
  if (f.Price && f.Price.startsWith("$")) {
    const n = Number(f.Price.replace(/[^0-9.]/g, ""));
    priceValue = !Number.isNaN(n) ? n : null;
  }

  // Rating: "4.7 (1346 reviews)" or "4.7 (N/A reviews)"
  let ratingValue: number | null = null;
  let reviewsValue: number | null = null;
  if (f.Rating) {
    const m = f.Rating.match(/^([\d.]+)\s*\(([^)]*)\)/);
    if (m) {
      ratingValue = Number(m[1]);
      const reviewsRaw = m[2].replace(/reviews/i, "").trim();
      if (reviewsRaw && reviewsRaw.toLowerCase() !== "n/a") {
        const rv = Number(reviewsRaw.replace(/[^0-9]/g, ""));
        reviewsValue = !Number.isNaN(rv) ? rv : null;
      }
    }
  }

  const qualityScore = Number(f["Quality Score"]) || 0;
  const priority = ((f.Priority || "C").trim() as "A" | "B" | "C");

  const secondary = (f["Secondary Keywords"] || "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
  const longTail = (f["Long-tail Keywords"] || "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);

  products.push({
    id: asin,
    asin,
    title: f.Title,
    category: f.Category,
    price: priceValue,
    priceDisplay: priceValue != null ? `$${priceValue.toFixed(2)}` : null,
    rating: ratingValue,
    reviews: reviewsValue,
    image: f.Image || "",
    affiliateUrl: f.URL,
    priority,
    qualityScore,
    mainKeyword: f["Main Keyword"] || "",
    secondaryKeywords: secondary,
    longTailKeywords: longTail,
    suggestedCalculator: f["Suggested Calculator"] || null,
  });
}

console.log(`Parsed ${products.length} products. (Skipped/header blocks: ${issues})`);
console.log("Sample 1:", JSON.stringify(products[0], null, 2));
console.log(
  "Sample N/A price:",
  JSON.stringify(products.find((p) => p.price === null), null, 2),
);
console.log("Categories:", [...new Set(products.map((p) => p.category))].sort().join(", "));
console.log("Calculators:", [...new Set(products.map((p) => p.suggestedCalculator).filter(Boolean))].sort().join(", "));

const lines: string[] = [];
lines.push(`// AUTO-GENERATED by scripts/parse-products.ts — do not edit by hand.`);
lines.push(`// Source: upload/fitfeky_products_172.txt (curated fitness products for women 40+)`);
lines.push(`import type { Product } from "./types";`);
lines.push(``);
lines.push(`export const products: Product[] = [`);

for (const p of products) {
  const pretty = JSON.stringify(p, null, 2);
  // indent every line by 2 spaces
  const indented = pretty.replace(/\n/g, "\n  ");
  lines.push(`  ${indented},`);
}

lines.push(`];`);
lines.push(``);
lines.push(`export const productCount = products.length;`);

writeFileSync(OUT, lines.join("\n"), "utf8");
console.log(`Wrote ${OUT} (${products.length} products)`);
